
# Site settings
title: Park School Mathematics
email: parkmathblog@parkschool.net
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/"
url: "http://parkmath.anandthakker.net" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude:
  - tools
  - temp
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules

# Content-specific settings
collections:
  books:
    output: true
  lessons:
    output: true

defaults:
  - scope:
      path: ""
      type: lessons
    values:
      layout: lesson # lesson | habit-lesson
      type: content # content | habit
      
  - scope:
      path: ""
      type: books
    values:
      layout: book


# Prose metadata
prose:
  rooturl: _lessons
  siteurl: "http://parkmath.github.io/parkmath"
  media: images
  metadata:
    _lessons:
      - name: book
        field:
          element: number
          label: Book Number
          value: 0
      - name: lesson
        field:
          element: number
          label: Lesson Number
          value: 0
      - name: title
        field:
          element: text
          label: Title
          value: ''
      - name: type
        field:
          element: select
          label: Type
          options:
            - content
            - habit
          value: content
          
      - name: layout
        field:
          element: hidden
          value: lesson
          
  
